### ISSUE TITLE
请问百度网盘好像登录不了呢

### ISSUE THREAD

**Issue by freddiezhao** [Panway/PandaNote#1]
一直提示网络无法连接

**Comment by Panway** [comment]
我把AppDelegate.swift的这两行用于HTTP资源拦截的注释掉，登录成功过一次，后来就再也没法成功了😓
``` swift
URLProtocol.registerClass(PPReplacingImageURLProtocol.self)
PPWebViewController.registerHTTPScheme()
```
我先看下百度网盘开放平台的文档，之前是全部抓包获取的API

**Comment by freddiezhao** [comment]
> 我把AppDelegate.swift的这两行用于HTTP资源拦截的注释掉，登录成功过一次，后来就再也没法成功了😓
> 
> ```swift
> URLProtocol.registerClass(PPReplacingImageURLProtocol.self)
> PPWebViewController.registerHTTPScheme()
> ```
> 
> 我先看下百度网盘开放平台的文档，之前是全部抓包获取的API

好的,我也研究一下,感觉就是请求被拦截了,没发出去,导致报无法连接的错误,谢谢回复哦

**Comment by Panway** [comment]
增加了Safari打开百度授权URL，然后返回App获取token，也更加安全，可以试下

**Comment by freddiezhao** [comment]
> 增加了Safari打开百度授权URL，然后返回App获取token，也更加安全，可以试下

嗯嗯,好的,谢谢,非常感谢

**Comment by freddiezhao** [comment]
> > 增加了Safari打开百度授权URL，然后返回App获取token，也更加安全，可以试下
> 
> 嗯嗯,好的,谢谢,非常感谢

我仔细看了一下,这几行代码改一下就可以了:

原来的写法:
  class func unregisterHTTPScheme() {
        for scheme in ["http", "https"] {
            URLProtocol.self.wk_registerScheme(scheme)
        }
    }

改成:

 class func unregisterHTTPScheme() {
        for scheme in ["http", "https"] {
            URLProtocol.self.wk_unregisterScheme(scheme)
        }
    }

另外不知道加这几行代码是啥意思,其实都删除就可以了.

**Comment by Panway** [comment]
你不说我还没注意到，wk_unregisterScheme 用于取消HTTP资源拦截的（百度授权登录的时候），忘了un这俩字母哈哈

**Comment by freddiezhao** [comment]
> 你不说我还没注意到，wk_unregisterScheme 用于取消HTTP资源拦截的（百度授权登录的时候），忘了un这俩字母哈哈

期待大佬继续完善这个项目哦,是一个非常好的项目
