### ISSUE TITLE
编译通不过，文件缺失

### ISSUE THREAD

**Issue by Monkey-X-Byte** [Panway/PandaNote#4]
UIKitTool 目录下俩个文件缺失

<img width="330" alt="image" src="https://user-images.githubusercontent.com/57513371/219595818-6ae790b7-08e5-4d7b-a94a-9bfaeed3c6a4.png">

**Comment by Panway** [comment]
@Monkey-X-Byte  代码提交了，你再试试看

**Comment by Panway** [comment]
iPad和macOS改为左右两栏显示
